### ISSUE TITLE
How deal with URI?

### ISSUE THREAD

**Issue by sanpii** [todotxt/todo.txt#15]
Hello,

It’s easy to ignore URL (ie `https://`) from keywords but how can we (parser writers) should deal with the others URI like `mailto:`, `tel:`, [etc.](https://en.wikipedia.org/wiki/Category:URI_schemes)?

**Comment by tomByrer** [comment]
Don't include the URI?

**Comment by tensau** [comment]
> Don't include the URI?

That's not a solution.

**Comment by TangentFoxy** [comment]
@sanpii Why do you want to ignore it? It's a valid key:value pair, just of an unusual nature. Personally I prefer to just accept protocols as commonly occurring key:value tags.
