### ISSUE TITLE
Didn't there used to be a mailing list for todo.txt?

### ISSUE THREAD

**Issue by GrouchyGaijin** [todotxt/todo.txt#19]
I cannot seem to find it now.

**Comment by chipbite** [comment]
Maybe 
https://groups.yahoo.com/neo/groups/todotxt/conversations/messages

**Comment by karbassi** [comment]
Yes, but since yahoo groups is no more, we have moved to [gitter](https://gitter.im/todotxt/todotxt). Not a full replacement, but good enough for now.
