### ISSUE TITLE
todotxt.js - TodoList.prototype.checkTerm logic is faulty

### ISSUE THREAD

**Issue by arprice102** [todotxt/todo.txt#32]
Towards the end of the function on line 677, the if statement reads:

**if (!case_sensitive)** {
  res = (task.text.indexOf(term) === -1) ? not : !not;
} else {
   res = (task.text.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()) === -1) ? not : !not;
}

It should actually read **if(case_sensitive)** - drop the !

You only want to convert to lower case if case_sensitive = false.

**Comment by karbassi** [comment]
Hello @arprice102 

Do you mean to submit this issue to https://github.com/roufamatic/todo-txt-js or https://github.com/rmasters/todotxt.js or https://github.com/jmhobbs/jsTodoTxt ?

This repository is for the todo.txt spec only.
