### ISSUE TITLE
Move tasks to done file is missing

### ISSUE THREAD

**Issue by buckleyGI** [todotxt/todo.txt#34]
Maybe this is a bug or maybe I don't understand.

Shouldn't there be a "Move tasks to done file"? here

![image](https://user-images.githubusercontent.com/2102864/98252345-198bde00-1f7a-11eb-97e4-7fc736e67aeb.png)

Thank you

**Comment by bobwhitelock** [comment]
This repo is for the todo.txt spec, which just describes the format. Looks like you're using an app for working with this format (a VS Code plugin?) and so you should probably log an issue on the repo for that instead

**Comment by karbassi** [comment]
@buckleyGI I assume you want the vscode extension: https://github.com/vamanos/todo-txt

**Comment by buckleyGI** [comment]
You are right. Excuse me 🙇‍♂️
