### ISSUE TITLE
description.svg is not showing correctly

### ISSUE THREAD

**Issue by ermats** [todotxt/todo.txt#59]
The lines describing a part in a todo.txt line are off, for example the context line points to the due date, as you can see on the screenshot.

![Screenshot_2021-03-16_10-33-38](https://user-images.githubusercontent.com/80751205/111287062-249afd00-8643-11eb-9329-15cd94e51c17.png)

**Comment by karbassi** [comment]
Looks good to me.

https://raw.githubusercontent.com/todotxt/todo.txt/master/description.svg

**Comment by ermats** [comment]
It looks good on chrome only, on Firefox it looks like in the image above.
